# Generated by Django 5.1 on 2024-12-03 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trocas_app', '0002_rename_date_troca_date_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='troca',
            old_name='date_color',
            new_name='color',
        ),
    ]
