# Generated by Django 5.1 on 2024-12-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='id_sucursal',
            field=models.IntegerField(default=1),
        ),
    ]
